services:
  - type: web
    name: diario-fitness-backend
    env: python
    pythonVersion: 3.10  # ✅ Inserito correttamente qui
    buildCommand: ""
    startCommand: gunicorn fitness_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nomeprogetto.settings

