# Generated by Django 5.2 on 2025-05-22 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarioalimentare',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='misurazione',
            name='altezza_cm',
        ),
        migrations.RemoveField(
            model_name='misurazione',
            name='sesso',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=10, null=True)),
                ('altezza', models.FloatField(blank=True, null=True)),
                ('immagine', models.ImageField(blank=True, default='blank-profile-male.jpg', null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
